package Frames;

import Logic.GestorHabitaciones;

/**
 *
 * @author JafetDG
 */
public class FrmHabitaciones extends javax.swing.JFrame {

    String numeroHabitacion = "1";
    String numeroHabitacion2 = "2";
    String numeroHabitacion3 = "3";
    String numeroHabitacion4 = "4";
    String numeroHabitacion5 = "5";
    String numeroHabitacion7 = "7";
    String numeroHabitacion8 = "8";
    String numeroHabitacion9 = "9";
    String numeroHabitacion10 = "10";
    String numeroHabitacion11 = "11";
    String numeroHabitacion12 = "12";
    String numeroHabitacion13 = "13";
    String numeroHabitacion14 = "14";
    String numeroHabitacion15 = "15";
    String numeroHabitacion16 = "16";
    String numeroHabitacion17 = "17";
    String numeroHabitacion18 = "18";
    String numeroHabitacion19 = "19";
    String numeroHabitacion20 = "20";
    String numeroHabitacion21 = "21";
    String numeroHabitacion22 = "22";
    String numeroHabitacion23 = "23";
    String numeroHabitacion24 = "24";
    String numeroHabitacion25 = "25";
    String numeroHabitacion26 = "26";
    String numeroHabitacion27 = "27";
    String numeroHabitacion28 = "28";
    String numeroHabitacion29 = "29";
    
    public FrmHabitaciones() {
        initComponents();
        setLocationRelativeTo(null);
        /*Al ejecutar el programa se abrirá en pantalla completa*/
        setExtendedState(MAXIMIZED_BOTH);
        cargarGrupoImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblMantenimiento = new javax.swing.JLabel();
        lblOcupada = new javax.swing.JLabel();
        lblLimpieza = new javax.swing.JLabel();
        lblVariosDias = new javax.swing.JLabel();
        lblReservada = new javax.swing.JLabel();
        lblHabitaciones = new javax.swing.JLabel();
        panelHabitaciones = new javax.swing.JPanel();
        scrollHabitaciones = new javax.swing.JScrollPane();
        panelScrollHab = new javax.swing.JPanel();
        panelPrimeraFila = new javax.swing.JPanel();
        lblN5 = new javax.swing.JLabel();
        lblN4 = new javax.swing.JLabel();
        lblN3 = new javax.swing.JLabel();
        lblN2 = new javax.swing.JLabel();
        lblN1 = new javax.swing.JLabel();
        panelSegundaFila = new javax.swing.JPanel();
        lblN10 = new javax.swing.JLabel();
        lblN9 = new javax.swing.JLabel();
        lblN8 = new javax.swing.JLabel();
        lblN7 = new javax.swing.JLabel();
        panelTerceraFila = new javax.swing.JPanel();
        lblN15 = new javax.swing.JLabel();
        lblN14 = new javax.swing.JLabel();
        lblN13 = new javax.swing.JLabel();
        lblN12 = new javax.swing.JLabel();
        lblN11 = new javax.swing.JLabel();
        panelCuartaFila = new javax.swing.JPanel();
        lblN20 = new javax.swing.JLabel();
        lblN19 = new javax.swing.JLabel();
        lblN18 = new javax.swing.JLabel();
        lblN17 = new javax.swing.JLabel();
        lblN16 = new javax.swing.JLabel();
        panelCuartaFila1 = new javax.swing.JPanel();
        lblN25 = new javax.swing.JLabel();
        lblN24 = new javax.swing.JLabel();
        lblN23 = new javax.swing.JLabel();
        lblN22 = new javax.swing.JLabel();
        lblN21 = new javax.swing.JLabel();
        panelCuartaFila2 = new javax.swing.JPanel();
        lblN29 = new javax.swing.JLabel();
        lblN28 = new javax.swing.JLabel();
        lblN27 = new javax.swing.JLabel();
        lblN26 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo (Personalizado).png"))); // NOI18N

        lblMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estados/mantenimiento_figma.png"))); // NOI18N

        lblOcupada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estados/ocupada_figma.png"))); // NOI18N

        lblLimpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estados/limpieza_figma.png"))); // NOI18N

        lblVariosDias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estados/variosdias_figma.png"))); // NOI18N

        lblReservada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estados/reservada_figma.png"))); // NOI18N

        lblHabitaciones.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblHabitaciones.setForeground(new java.awt.Color(0, 0, 0));
        lblHabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labels/Habitaciones.png"))); // NOI18N

        panelHabitaciones.setBackground(new java.awt.Color(255, 255, 255));

        scrollHabitaciones.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelScrollHab.setBackground(new java.awt.Color(255, 255, 255));

        panelPrimeraFila.setBackground(new java.awt.Color(255, 255, 255));

        lblN5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n5Disponible.png"))); // NOI18N
        lblN5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN5MouseClicked(evt);
            }
        });

        lblN4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n4Disponible.png"))); // NOI18N
        lblN4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN4MouseClicked(evt);
            }
        });

        lblN3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n3Disponible.png"))); // NOI18N
        lblN3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN3MouseClicked(evt);
            }
        });

        lblN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n2Disponible.png"))); // NOI18N
        lblN2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN2MouseClicked(evt);
            }
        });

        lblN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n1Disponible.png"))); // NOI18N
        lblN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelPrimeraFilaLayout = new javax.swing.GroupLayout(panelPrimeraFila);
        panelPrimeraFila.setLayout(panelPrimeraFilaLayout);
        panelPrimeraFilaLayout.setHorizontalGroup(
            panelPrimeraFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrimeraFilaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblN1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(lblN2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(lblN3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(lblN4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lblN5)
                .addGap(25, 25, 25))
        );
        panelPrimeraFilaLayout.setVerticalGroup(
            panelPrimeraFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrimeraFilaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelPrimeraFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblN5)
                    .addGroup(panelPrimeraFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblN4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblN3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblN2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblN1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSegundaFila.setBackground(new java.awt.Color(255, 255, 255));

        lblN10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n10Disponible.png"))); // NOI18N
        lblN10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN10MouseClicked(evt);
            }
        });

        lblN9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n9Disponible.png"))); // NOI18N
        lblN9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN9MouseClicked(evt);
            }
        });

        lblN8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n8Disponible.png"))); // NOI18N
        lblN8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN8MouseClicked(evt);
            }
        });

        lblN7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n7Disponible.png"))); // NOI18N
        lblN7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelSegundaFilaLayout = new javax.swing.GroupLayout(panelSegundaFila);
        panelSegundaFila.setLayout(panelSegundaFilaLayout);
        panelSegundaFilaLayout.setHorizontalGroup(
            panelSegundaFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSegundaFilaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblN7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblN8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblN9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblN10)
                .addGap(25, 25, 25))
        );
        panelSegundaFilaLayout.setVerticalGroup(
            panelSegundaFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSegundaFilaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelSegundaFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblN10)
                    .addGroup(panelSegundaFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblN9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblN8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblN7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTerceraFila.setBackground(new java.awt.Color(255, 255, 255));

        lblN15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n15Disponible.png"))); // NOI18N
        lblN15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN15MouseClicked(evt);
            }
        });

        lblN14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n14Disponible.png"))); // NOI18N
        lblN14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN14MouseClicked(evt);
            }
        });

        lblN13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n13Disponible.png"))); // NOI18N
        lblN13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN13MouseClicked(evt);
            }
        });

        lblN12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n12Disponible.png"))); // NOI18N
        lblN12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN12MouseClicked(evt);
            }
        });

        lblN11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n11Disponible.png"))); // NOI18N
        lblN11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTerceraFilaLayout = new javax.swing.GroupLayout(panelTerceraFila);
        panelTerceraFila.setLayout(panelTerceraFilaLayout);
        panelTerceraFilaLayout.setHorizontalGroup(
            panelTerceraFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTerceraFilaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblN11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblN12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblN13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblN14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblN15)
                .addGap(25, 25, 25))
        );
        panelTerceraFilaLayout.setVerticalGroup(
            panelTerceraFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTerceraFilaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelTerceraFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblN15)
                    .addGroup(panelTerceraFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblN14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblN13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblN12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblN11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCuartaFila.setBackground(new java.awt.Color(255, 255, 255));

        lblN20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n20Disponible.png"))); // NOI18N
        lblN20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN20MouseClicked(evt);
            }
        });

        lblN19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n19Disponible.png"))); // NOI18N
        lblN19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN19MouseClicked(evt);
            }
        });

        lblN18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n18Disponible.png"))); // NOI18N
        lblN18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN18MouseClicked(evt);
            }
        });

        lblN17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n17Disponible.png"))); // NOI18N
        lblN17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN17MouseClicked(evt);
            }
        });

        lblN16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n16Disponible.png"))); // NOI18N
        lblN16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCuartaFilaLayout = new javax.swing.GroupLayout(panelCuartaFila);
        panelCuartaFila.setLayout(panelCuartaFilaLayout);
        panelCuartaFilaLayout.setHorizontalGroup(
            panelCuartaFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuartaFilaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblN16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblN17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblN18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblN19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblN20)
                .addGap(25, 25, 25))
        );
        panelCuartaFilaLayout.setVerticalGroup(
            panelCuartaFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuartaFilaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelCuartaFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblN20)
                    .addGroup(panelCuartaFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblN19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblN18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblN17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblN16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCuartaFila1.setBackground(new java.awt.Color(255, 255, 255));

        lblN25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n25Disponible.png"))); // NOI18N
        lblN25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN25MouseClicked(evt);
            }
        });

        lblN24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n24Disponible.png"))); // NOI18N
        lblN24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN24MouseClicked(evt);
            }
        });

        lblN23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n23Disponible.png"))); // NOI18N
        lblN23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN23MouseClicked(evt);
            }
        });

        lblN22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n22Disponible.png"))); // NOI18N
        lblN22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN22MouseClicked(evt);
            }
        });

        lblN21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n21Disponible.png"))); // NOI18N
        lblN21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN21MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCuartaFila1Layout = new javax.swing.GroupLayout(panelCuartaFila1);
        panelCuartaFila1.setLayout(panelCuartaFila1Layout);
        panelCuartaFila1Layout.setHorizontalGroup(
            panelCuartaFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuartaFila1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblN21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblN22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblN23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblN24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblN25)
                .addGap(25, 25, 25))
        );
        panelCuartaFila1Layout.setVerticalGroup(
            panelCuartaFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuartaFila1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelCuartaFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblN25)
                    .addGroup(panelCuartaFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblN24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblN23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblN22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblN21)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCuartaFila2.setBackground(new java.awt.Color(255, 255, 255));

        lblN29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n29Disponible.png"))); // NOI18N
        lblN29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN29MouseClicked(evt);
            }
        });

        lblN28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n28Disponible.png"))); // NOI18N
        lblN28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN28MouseClicked(evt);
            }
        });

        lblN27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n27Disponible.png"))); // NOI18N
        lblN27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN27MouseClicked(evt);
            }
        });

        lblN26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/habitaciones/n26Disponible.png"))); // NOI18N
        lblN26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN26MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCuartaFila2Layout = new javax.swing.GroupLayout(panelCuartaFila2);
        panelCuartaFila2.setLayout(panelCuartaFila2Layout);
        panelCuartaFila2Layout.setHorizontalGroup(
            panelCuartaFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuartaFila2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblN26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblN27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblN28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblN29)
                .addGap(48, 48, 48))
        );
        panelCuartaFila2Layout.setVerticalGroup(
            panelCuartaFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuartaFila2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelCuartaFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblN29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblN28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblN27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblN26))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelScrollHabLayout = new javax.swing.GroupLayout(panelScrollHab);
        panelScrollHab.setLayout(panelScrollHabLayout);
        panelScrollHabLayout.setHorizontalGroup(
            panelScrollHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrimeraFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelScrollHabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelScrollHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSegundaFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTerceraFila, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCuartaFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCuartaFila1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCuartaFila2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelScrollHabLayout.setVerticalGroup(
            panelScrollHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScrollHabLayout.createSequentialGroup()
                .addComponent(panelPrimeraFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelSegundaFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTerceraFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelCuartaFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCuartaFila1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCuartaFila2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        scrollHabitaciones.setViewportView(panelScrollHab);

        javax.swing.GroupLayout panelHabitacionesLayout = new javax.swing.GroupLayout(panelHabitaciones);
        panelHabitaciones.setLayout(panelHabitacionesLayout);
        panelHabitacionesLayout.setHorizontalGroup(
            panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollHabitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        panelHabitacionesLayout.setVerticalGroup(
            panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHabitacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollHabitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))
        );

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btnRegresar.png"))); // NOI18N
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMantenimiento)
                    .addComponent(lblOcupada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVariosDias)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblLimpieza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblReservada)))
                .addGap(18, 18, 18)
                .addComponent(lblHabitaciones)
                .addContainerGap())
            .addComponent(panelHabitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblMantenimiento)
                                        .addComponent(lblLimpieza, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(lblReservada))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOcupada)
                                    .addComponent(lblVariosDias)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                                .addComponent(lblHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                                .addComponent(btnRegresar)
                                .addGap(29, 29, 29)))))
                .addComponent(panelHabitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarGrupoImagenes() {
        GestorHabitaciones.cargarImagenSegunEstado(lblN1, numeroHabitacion);
        GestorHabitaciones.cargarImagenSegunEstado(lblN2, numeroHabitacion2);
        GestorHabitaciones.cargarImagenSegunEstado(lblN3, numeroHabitacion3);
        GestorHabitaciones.cargarImagenSegunEstado(lblN4, numeroHabitacion4);
        GestorHabitaciones.cargarImagenSegunEstado(lblN5, numeroHabitacion5);
        GestorHabitaciones.cargarImagenSegunEstado(lblN7, numeroHabitacion7);
        GestorHabitaciones.cargarImagenSegunEstado(lblN8, numeroHabitacion8);
        GestorHabitaciones.cargarImagenSegunEstado(lblN9, numeroHabitacion9);
        GestorHabitaciones.cargarImagenSegunEstado(lblN10, numeroHabitacion10);
        GestorHabitaciones.cargarImagenSegunEstado(lblN11, numeroHabitacion11);
        GestorHabitaciones.cargarImagenSegunEstado(lblN12, numeroHabitacion12);
        GestorHabitaciones.cargarImagenSegunEstado(lblN13, numeroHabitacion13);
        GestorHabitaciones.cargarImagenSegunEstado(lblN14, numeroHabitacion14);
        GestorHabitaciones.cargarImagenSegunEstado(lblN15, numeroHabitacion15);
        GestorHabitaciones.cargarImagenSegunEstado(lblN16, numeroHabitacion16);
        GestorHabitaciones.cargarImagenSegunEstado(lblN17, numeroHabitacion17);
        GestorHabitaciones.cargarImagenSegunEstado(lblN18, numeroHabitacion18);
        GestorHabitaciones.cargarImagenSegunEstado(lblN19, numeroHabitacion19);
        GestorHabitaciones.cargarImagenSegunEstado(lblN20, numeroHabitacion20);
        GestorHabitaciones.cargarImagenSegunEstado(lblN21, numeroHabitacion21);
        GestorHabitaciones.cargarImagenSegunEstado(lblN22, numeroHabitacion22);
        GestorHabitaciones.cargarImagenSegunEstado(lblN23, numeroHabitacion23);
        GestorHabitaciones.cargarImagenSegunEstado(lblN24, numeroHabitacion24);
        GestorHabitaciones.cargarImagenSegunEstado(lblN25, numeroHabitacion25);
        GestorHabitaciones.cargarImagenSegunEstado(lblN26, numeroHabitacion26);
        GestorHabitaciones.cargarImagenSegunEstado(lblN27, numeroHabitacion27);
        GestorHabitaciones.cargarImagenSegunEstado(lblN28, numeroHabitacion28);
        GestorHabitaciones.cargarImagenSegunEstado(lblN29, numeroHabitacion29);
    }

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        FrmPrincipal princi = new FrmPrincipal();
        princi.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void lblN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN1MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN1, numeroHabitacion);
    }//GEN-LAST:event_lblN1MouseClicked

    private void lblN2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN2MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN2, numeroHabitacion2);
    }//GEN-LAST:event_lblN2MouseClicked

    private void lblN3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN3MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN3, numeroHabitacion3);
    }//GEN-LAST:event_lblN3MouseClicked

    private void lblN4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN4MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN4, numeroHabitacion4);
    }//GEN-LAST:event_lblN4MouseClicked

    private void lblN5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN5MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN5, numeroHabitacion5);
    }//GEN-LAST:event_lblN5MouseClicked

    private void lblN7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN7MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN7, numeroHabitacion7);
    }//GEN-LAST:event_lblN7MouseClicked

    private void lblN8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN8MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN8, numeroHabitacion8);
    }//GEN-LAST:event_lblN8MouseClicked

    private void lblN9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN9MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN9, numeroHabitacion9);
    }//GEN-LAST:event_lblN9MouseClicked

    private void lblN10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN10MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN10, numeroHabitacion10);
    }//GEN-LAST:event_lblN10MouseClicked

    private void lblN11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN11MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN11, numeroHabitacion11);
    }//GEN-LAST:event_lblN11MouseClicked

    private void lblN12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN12MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN12, numeroHabitacion12);
    }//GEN-LAST:event_lblN12MouseClicked

    private void lblN13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN13MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN13, numeroHabitacion13);
    }//GEN-LAST:event_lblN13MouseClicked

    private void lblN14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN14MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN14, numeroHabitacion14);
    }//GEN-LAST:event_lblN14MouseClicked

    private void lblN15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN15MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN15, numeroHabitacion15);
    }//GEN-LAST:event_lblN15MouseClicked

    private void lblN16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN16MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN16, numeroHabitacion16);
    }//GEN-LAST:event_lblN16MouseClicked

    private void lblN17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN17MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN17, numeroHabitacion17);
    }//GEN-LAST:event_lblN17MouseClicked

    private void lblN18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN18MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN18, numeroHabitacion18);
    }//GEN-LAST:event_lblN18MouseClicked

    private void lblN19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN19MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN19, numeroHabitacion19);
    }//GEN-LAST:event_lblN19MouseClicked

    private void lblN20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN20MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN20, numeroHabitacion20);
    }//GEN-LAST:event_lblN20MouseClicked

    private void lblN21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN21MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN21, numeroHabitacion21);
    }//GEN-LAST:event_lblN21MouseClicked

    private void lblN22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN22MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN22, numeroHabitacion22);
    }//GEN-LAST:event_lblN22MouseClicked

    private void lblN23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN23MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN23, numeroHabitacion23);
    }//GEN-LAST:event_lblN23MouseClicked

    private void lblN24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN24MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN24, numeroHabitacion24);
    }//GEN-LAST:event_lblN24MouseClicked

    private void lblN25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN25MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN25, numeroHabitacion25);
    }//GEN-LAST:event_lblN25MouseClicked

    private void lblN26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN26MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN26, numeroHabitacion26);
    }//GEN-LAST:event_lblN26MouseClicked

    private void lblN27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN27MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN27, numeroHabitacion27);
    }//GEN-LAST:event_lblN27MouseClicked

    private void lblN28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN28MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN28, numeroHabitacion28);
    }//GEN-LAST:event_lblN28MouseClicked

    private void lblN29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN29MouseClicked
        GestorHabitaciones.manejarClicHabitacion(lblN29, numeroHabitacion29);
    }//GEN-LAST:event_lblN29MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHabitaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnRegresar;
    private javax.swing.JLabel lblHabitaciones;
    private javax.swing.JLabel lblLimpieza;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMantenimiento;
    private javax.swing.JLabel lblN1;
    private javax.swing.JLabel lblN10;
    private javax.swing.JLabel lblN11;
    private javax.swing.JLabel lblN12;
    private javax.swing.JLabel lblN13;
    private javax.swing.JLabel lblN14;
    private javax.swing.JLabel lblN15;
    private javax.swing.JLabel lblN16;
    private javax.swing.JLabel lblN17;
    private javax.swing.JLabel lblN18;
    private javax.swing.JLabel lblN19;
    private javax.swing.JLabel lblN2;
    private javax.swing.JLabel lblN20;
    private javax.swing.JLabel lblN21;
    private javax.swing.JLabel lblN22;
    private javax.swing.JLabel lblN23;
    private javax.swing.JLabel lblN24;
    private javax.swing.JLabel lblN25;
    private javax.swing.JLabel lblN26;
    private javax.swing.JLabel lblN27;
    private javax.swing.JLabel lblN28;
    private javax.swing.JLabel lblN29;
    private javax.swing.JLabel lblN3;
    private javax.swing.JLabel lblN4;
    private javax.swing.JLabel lblN5;
    private javax.swing.JLabel lblN7;
    private javax.swing.JLabel lblN8;
    private javax.swing.JLabel lblN9;
    private javax.swing.JLabel lblOcupada;
    private javax.swing.JLabel lblReservada;
    private javax.swing.JLabel lblVariosDias;
    private javax.swing.JPanel panelCuartaFila;
    private javax.swing.JPanel panelCuartaFila1;
    private javax.swing.JPanel panelCuartaFila2;
    private javax.swing.JPanel panelHabitaciones;
    private javax.swing.JPanel panelPrimeraFila;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelScrollHab;
    private javax.swing.JPanel panelSegundaFila;
    private javax.swing.JPanel panelTerceraFila;
    private javax.swing.JScrollPane scrollHabitaciones;
    // End of variables declaration//GEN-END:variables
}
